#!/bin/bash

SCRIPT_DIR=$(realpath $(dirname $0))




ROOT="${SCRIPT_DIR}"

LIBS=("SystemHelpers/SystemHelpers.cpp")
LIBS+=("StringHelpers/StringHelpers.cpp")
LIBS+=("FilesystemHelpers/FilesystemHelpers.cpp")


OBJS="${ROOT}/obj"


INCLUDE="-I ${ROOT} "

for lib in "${LIBS[@]}"
do
    INCLUDE+="-I $(dirname ${ROOT}/${lib}) "
done


BUILD_FLAGS="-std=c++17"


if [ -d "$OBJS" ];
then
    rm -r "$OBJS"
fi

mkdir -p "$OBJS"


echo "Building libs ..."
echo "-----------------"
echo ""

for lib in "${LIBS[@]}"
do
    lib_path="${ROOT}/${lib}"
    lib_dir="$(dirname ${lib_path})"
    lib="$(basename ${lib})"

    echo "Entering ${lib_dir} ..."
    echo ""

    cd "${lib_dir}"
    clang++ -c ${lib} -o "${OBJS}/$(basename ${lib} .cpp).o" ${INCLUDE} ${BUILD_FLAGS}

    if ! [ "$?" == "0" ];
    then
        echo ""
        echo "Build failed."
        echo ""
        exit 1
    fi

    cd "${ROOT}"
done

echo ""
echo "All libs are built."
echo ""
