#!/bin/bash

SCRIPT_PATH=$(realpath $(dirname $0))



REPO="https://raw.githubusercontent.com/arithesage/cpp_libs/refs/heads/main"

LIBS=("FilesystemHelpers/FilesystemHelpers.hpp" \
      "FilesystemHelpers/FilesystemHelpers.cpp" \
      "StringHelpers/StringHelpers.hpp" \
      "StringHelpers/StringHelpers.cpp" \
      "SystemHelpers/SystemHelpers.hpp" \
      "SystemHelpers/SystemHelpers.cpp" \
      "VectorHelpers.hpp" \
      "LangHelpers.hpp" \
      "Types.hpp")


echo "Syncing libs..."
echo "---------------"

cd "$SCRIPT_PATH"

for lib in "${LIBS[@]}"
do
    lib_dir="$(dirname $lib)"

    if ! [ "$lib_dir" == "." ] && ! [ -d "$lib_dir" ];
    then
        mkdir -p "$lib_dir"
    fi

    if ! [ "$lib_dir" == "." ];
    then
        cd "$lib_dir"
    fi

    wget -N "$REPO/$lib"

    if ! [ "$lib_dir" == "." ];
    then
        cd ..
    fi
done
